name: Build and test installation
on:
  pull-request:
  push:
    branch:
    - 'main'

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
    steps:    
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: Install
      run: pip install -e .
    - name: Test durin import
      run: python3 -c "import durin"